### ISSUE TITLE
Free & Open Source Day

### ISSUE THREAD

**Issue by duttakapil** [coderplex/meetups#3]
Description : All Open Source enthusiasts from Hyderabad, beginners as well as advanced, come down together to contribute to open source projects. We finalize the projects before hand, based on which projects the mentors from our developer ecosystem actively contribute to. Attendees form groups around each project, and the mentor guides them in-person on contributing to the respective project.

Beginners get a free introduction to Git and GitHub

### ToDo for the event
- [ ] Finalize date : 11th March 2018
- [ ] Time : 10 am - 5 pm
- [ ] Confirm venue : IIIT-H
- [ ] Confirm list of projects and mentors (looking for more)
- [ ] Confirm partner communities
- [ ] Create website for event
- [ ] Design poster(s) 
- [ ] Food sponsorship
- [ ] Swag sponsorship

Resources : 
- [Try Git, interactive online bigener-friendly Git simulator](https://try.github.com)
- [Git It](http://jlord.us/git-it/)
- [Atlassian Guide's on Git](https://www.atlassian.com/git/tutorials)
- [Open Source Guides](https://opensource.guide/)
- [First Timers Only issues](http://www.firsttimersonly.com/)
- [List of awesome beginners-friendly open source projects](https://github.com/MunGell/awesome-for-beginners)
- [IssueHub : Find and contribute to GitHub Issues](http://issuehub.io/)
- [Open Hatch : Non-profit org for open source contributors](https://openhatch.org/)
- [Course on How to Contribute to Open Source Projects on GitHub](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github)
- [Libraries.io, search and find Open Source projects](https://libraries.io/)
- [Up For Grabs : Find open issues looking for new contributors](http://up-for-grabs.net)

Discuss any ideas or questions related to this event below

**Comment by duttakapil** [comment]
We should have certain metrics in place to measure the value produced by the meetup. 
For example : 

### Quantitative 
- Number of PR's made and merged
- Number of issues created and fixed

### Qualitative 
- For contributors
    - What value has Open Source Day added to you? 
    - Other than how to contribute to Open Source, what else did you learn?
    - How likely is it for you to continue making Open Source contributions?
    -  Would you recommend your friends to participate in Open Source Day? If not, why not?

**Comment by duttakapil** [comment]
Suggestions for mentors / projects from our Hackertoberfest Hyderabad event : 
- OpenRank mentored by Buddha
- Preact mentored by Prateek
- OpenStreetMaps mentored by Srinivas
- Jupyter Notebook mentored by Madhu
- IoT Open Source mentionred by IoT Hyderabad

**Comment by duttakapil** [comment]
Confirmed mentors : 
- Buddha (https://github.com/jbuddha) : Java
- Zubair (http://github.com/M-ZubairAhmed) : React 
- Bharath (https://github.com/bharaththiruveedula) : OpenStack
- Goutham (https://github.com/pratapaprasanna) : OpenStack

**Comment by Niveshkrishna** [comment]
Any updates over here?

**Comment by duttakapil** [comment]
@Niveshkrishna other than few more mentors joining, not much. Meetup is happening tomorrow at Swecha, with the mentors listed above, and few more from ThoughtWorks I believe
